/*
Application Principal Management Service

Handles all administrative requests to manage application identities, including both Agents and Service principals.

API version: 1.0
Contact: info@appdynamics.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package applicationprincipalmanagement

import (
	"encoding/json"
)

// BaseClientResponseCreate struct for BaseClientResponseCreate
type BaseClientResponseCreate struct {
	// The display name for the client.
	DisplayName *string `json:"displayName,omitempty"`
	// A user provided description of the client.
	Description *string `json:"description,omitempty"`
	// Supported authentication methods used to request oAuth tokens: * `client_secret_basic` - The client credentials will be sent in the authorization header. * `client_secret_post` - The client credentials will be sent in the request body.
	AuthType *string `json:"authType,omitempty"`
	// The unique client identifier.
	Id *string `json:"id,omitempty"`
	// Indicates if the client has rotated secrets. Rotated client secrets can be revoked.
	HasRotatedSecrets *bool `json:"hasRotatedSecrets,omitempty"`
	// The RFC3339 timestamp when the client was created.
	CreatedAt *string `json:"createdAt,omitempty"`
	// The RFC3339 timestamp when the client was last updated.
	UpdatedAt *string `json:"updatedAt,omitempty"`
	// The client's secret, used to authenticate during an oAuth token request.
	ClientSecret *string `json:"clientSecret,omitempty"`
}

// NewBaseClientResponseCreate instantiates a new BaseClientResponseCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseClientResponseCreate() *BaseClientResponseCreate {
	this := BaseClientResponseCreate{}
	return &this
}

// NewBaseClientResponseCreateWithDefaults instantiates a new BaseClientResponseCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseClientResponseCreateWithDefaults() *BaseClientResponseCreate {
	this := BaseClientResponseCreate{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *BaseClientResponseCreate) GetDisplayName() string {
	if o == nil || isNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseClientResponseCreate) GetDisplayNameOk() (*string, bool) {
	if o == nil || isNil(o.DisplayName) {
    return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *BaseClientResponseCreate) HasDisplayName() bool {
	if o != nil && !isNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *BaseClientResponseCreate) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *BaseClientResponseCreate) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseClientResponseCreate) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
    return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *BaseClientResponseCreate) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *BaseClientResponseCreate) SetDescription(v string) {
	o.Description = &v
}

// GetAuthType returns the AuthType field value if set, zero value otherwise.
func (o *BaseClientResponseCreate) GetAuthType() string {
	if o == nil || isNil(o.AuthType) {
		var ret string
		return ret
	}
	return *o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseClientResponseCreate) GetAuthTypeOk() (*string, bool) {
	if o == nil || isNil(o.AuthType) {
    return nil, false
	}
	return o.AuthType, true
}

// HasAuthType returns a boolean if a field has been set.
func (o *BaseClientResponseCreate) HasAuthType() bool {
	if o != nil && !isNil(o.AuthType) {
		return true
	}

	return false
}

// SetAuthType gets a reference to the given string and assigns it to the AuthType field.
func (o *BaseClientResponseCreate) SetAuthType(v string) {
	o.AuthType = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BaseClientResponseCreate) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseClientResponseCreate) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BaseClientResponseCreate) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *BaseClientResponseCreate) SetId(v string) {
	o.Id = &v
}

// GetHasRotatedSecrets returns the HasRotatedSecrets field value if set, zero value otherwise.
func (o *BaseClientResponseCreate) GetHasRotatedSecrets() bool {
	if o == nil || isNil(o.HasRotatedSecrets) {
		var ret bool
		return ret
	}
	return *o.HasRotatedSecrets
}

// GetHasRotatedSecretsOk returns a tuple with the HasRotatedSecrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseClientResponseCreate) GetHasRotatedSecretsOk() (*bool, bool) {
	if o == nil || isNil(o.HasRotatedSecrets) {
    return nil, false
	}
	return o.HasRotatedSecrets, true
}

// HasHasRotatedSecrets returns a boolean if a field has been set.
func (o *BaseClientResponseCreate) HasHasRotatedSecrets() bool {
	if o != nil && !isNil(o.HasRotatedSecrets) {
		return true
	}

	return false
}

// SetHasRotatedSecrets gets a reference to the given bool and assigns it to the HasRotatedSecrets field.
func (o *BaseClientResponseCreate) SetHasRotatedSecrets(v bool) {
	o.HasRotatedSecrets = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *BaseClientResponseCreate) GetCreatedAt() string {
	if o == nil || isNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseClientResponseCreate) GetCreatedAtOk() (*string, bool) {
	if o == nil || isNil(o.CreatedAt) {
    return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *BaseClientResponseCreate) HasCreatedAt() bool {
	if o != nil && !isNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *BaseClientResponseCreate) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *BaseClientResponseCreate) GetUpdatedAt() string {
	if o == nil || isNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseClientResponseCreate) GetUpdatedAtOk() (*string, bool) {
	if o == nil || isNil(o.UpdatedAt) {
    return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *BaseClientResponseCreate) HasUpdatedAt() bool {
	if o != nil && !isNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *BaseClientResponseCreate) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *BaseClientResponseCreate) GetClientSecret() string {
	if o == nil || isNil(o.ClientSecret) {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseClientResponseCreate) GetClientSecretOk() (*string, bool) {
	if o == nil || isNil(o.ClientSecret) {
    return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *BaseClientResponseCreate) HasClientSecret() bool {
	if o != nil && !isNil(o.ClientSecret) {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *BaseClientResponseCreate) SetClientSecret(v string) {
	o.ClientSecret = &v
}

func (o BaseClientResponseCreate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !isNil(o.AuthType) {
		toSerialize["authType"] = o.AuthType
	}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.HasRotatedSecrets) {
		toSerialize["hasRotatedSecrets"] = o.HasRotatedSecrets
	}
	if !isNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !isNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !isNil(o.ClientSecret) {
		toSerialize["clientSecret"] = o.ClientSecret
	}
	return json.Marshal(toSerialize)
}

type NullableBaseClientResponseCreate struct {
	value *BaseClientResponseCreate
	isSet bool
}

func (v NullableBaseClientResponseCreate) Get() *BaseClientResponseCreate {
	return v.value
}

func (v *NullableBaseClientResponseCreate) Set(val *BaseClientResponseCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseClientResponseCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseClientResponseCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseClientResponseCreate(val *BaseClientResponseCreate) *NullableBaseClientResponseCreate {
	return &NullableBaseClientResponseCreate{value: val, isSet: true}
}

func (v NullableBaseClientResponseCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseClientResponseCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


