// Copyright 2023 Cisco Systems, Inc.
// 
// Licensed under the MPL License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     https://www.mozilla.org/en-US/MPL/2.0/
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
/*
Application Principal Management Service

Handles all administrative requests to manage application identities, including both Agents and Service principals.

API version: 1.0
Contact: info@appdynamics.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package applicationprincipalmanagement

import (
	"encoding/json"
)

// RotationRequest struct for RotationRequest
type RotationRequest struct {
	// An ISO-8601 duration for how long the rotated secret will last before expiring. Input can not exceed 30 days. If not specified, defaults to 30 days.
	RevokeRotatedAfter interface{} `json:"revokeRotatedAfter,omitempty"`
}

// NewRotationRequest instantiates a new RotationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRotationRequest() *RotationRequest {
	this := RotationRequest{}
	return &this
}

// NewRotationRequestWithDefaults instantiates a new RotationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRotationRequestWithDefaults() *RotationRequest {
	this := RotationRequest{}
	return &this
}

// GetRevokeRotatedAfter returns the RevokeRotatedAfter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RotationRequest) GetRevokeRotatedAfter() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.RevokeRotatedAfter
}

// GetRevokeRotatedAfterOk returns a tuple with the RevokeRotatedAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RotationRequest) GetRevokeRotatedAfterOk() (*interface{}, bool) {
	if o == nil || isNil(o.RevokeRotatedAfter) {
    return nil, false
	}
	return &o.RevokeRotatedAfter, true
}

// HasRevokeRotatedAfter returns a boolean if a field has been set.
func (o *RotationRequest) HasRevokeRotatedAfter() bool {
	if o != nil && isNil(o.RevokeRotatedAfter) {
		return true
	}

	return false
}

// SetRevokeRotatedAfter gets a reference to the given interface{} and assigns it to the RevokeRotatedAfter field.
func (o *RotationRequest) SetRevokeRotatedAfter(v interface{}) {
	o.RevokeRotatedAfter = v
}

func (o RotationRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.RevokeRotatedAfter != nil {
		toSerialize["revokeRotatedAfter"] = o.RevokeRotatedAfter
	}
	return json.Marshal(toSerialize)
}

type NullableRotationRequest struct {
	value *RotationRequest
	isSet bool
}

func (v NullableRotationRequest) Get() *RotationRequest {
	return v.value
}

func (v *NullableRotationRequest) Set(val *RotationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRotationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRotationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRotationRequest(val *RotationRequest) *NullableRotationRequest {
	return &NullableRotationRequest{value: val, isSet: true}
}

func (v NullableRotationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRotationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


