/*
Application Principal Management Service

Handles all administrative requests to manage application identities, including both Agents and Service principals.

API version: 1.0
Contact: info@appdynamics.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package applicationprincipalmanagement

import (
	"encoding/json"
)

// BaseClientResponse struct for BaseClientResponse
type BaseClientResponse struct {
	// The display name for the client.
	DisplayName *string `json:"displayName,omitempty"`
	// A user provided description of the client.
	Description *string `json:"description,omitempty"`
	// Supported authentication methods used to request oAuth tokens: * `client_secret_basic` - The client credentials will be sent in the authorization header. * `client_secret_post` - The client credentials will be sent in the request body.
	AuthType *string `json:"authType,omitempty"`
	// The unique client identifier.
	Id *string `json:"id,omitempty"`
	// Indicates if the client has rotated secrets. Rotated client secrets can be revoked.
	HasRotatedSecrets *bool `json:"hasRotatedSecrets,omitempty"`
	// The RFC3339 timestamp when the client was created.
	CreatedAt *string `json:"createdAt,omitempty"`
	// The RFC3339 timestamp when the client was last updated.
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

// NewBaseClientResponse instantiates a new BaseClientResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseClientResponse() *BaseClientResponse {
	this := BaseClientResponse{}
	return &this
}

// NewBaseClientResponseWithDefaults instantiates a new BaseClientResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseClientResponseWithDefaults() *BaseClientResponse {
	this := BaseClientResponse{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *BaseClientResponse) GetDisplayName() string {
	if o == nil || isNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseClientResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil || isNil(o.DisplayName) {
    return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *BaseClientResponse) HasDisplayName() bool {
	if o != nil && !isNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *BaseClientResponse) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *BaseClientResponse) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseClientResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
    return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *BaseClientResponse) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *BaseClientResponse) SetDescription(v string) {
	o.Description = &v
}

// GetAuthType returns the AuthType field value if set, zero value otherwise.
func (o *BaseClientResponse) GetAuthType() string {
	if o == nil || isNil(o.AuthType) {
		var ret string
		return ret
	}
	return *o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseClientResponse) GetAuthTypeOk() (*string, bool) {
	if o == nil || isNil(o.AuthType) {
    return nil, false
	}
	return o.AuthType, true
}

// HasAuthType returns a boolean if a field has been set.
func (o *BaseClientResponse) HasAuthType() bool {
	if o != nil && !isNil(o.AuthType) {
		return true
	}

	return false
}

// SetAuthType gets a reference to the given string and assigns it to the AuthType field.
func (o *BaseClientResponse) SetAuthType(v string) {
	o.AuthType = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BaseClientResponse) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseClientResponse) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BaseClientResponse) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *BaseClientResponse) SetId(v string) {
	o.Id = &v
}

// GetHasRotatedSecrets returns the HasRotatedSecrets field value if set, zero value otherwise.
func (o *BaseClientResponse) GetHasRotatedSecrets() bool {
	if o == nil || isNil(o.HasRotatedSecrets) {
		var ret bool
		return ret
	}
	return *o.HasRotatedSecrets
}

// GetHasRotatedSecretsOk returns a tuple with the HasRotatedSecrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseClientResponse) GetHasRotatedSecretsOk() (*bool, bool) {
	if o == nil || isNil(o.HasRotatedSecrets) {
    return nil, false
	}
	return o.HasRotatedSecrets, true
}

// HasHasRotatedSecrets returns a boolean if a field has been set.
func (o *BaseClientResponse) HasHasRotatedSecrets() bool {
	if o != nil && !isNil(o.HasRotatedSecrets) {
		return true
	}

	return false
}

// SetHasRotatedSecrets gets a reference to the given bool and assigns it to the HasRotatedSecrets field.
func (o *BaseClientResponse) SetHasRotatedSecrets(v bool) {
	o.HasRotatedSecrets = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *BaseClientResponse) GetCreatedAt() string {
	if o == nil || isNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseClientResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || isNil(o.CreatedAt) {
    return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *BaseClientResponse) HasCreatedAt() bool {
	if o != nil && !isNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *BaseClientResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *BaseClientResponse) GetUpdatedAt() string {
	if o == nil || isNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseClientResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil || isNil(o.UpdatedAt) {
    return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *BaseClientResponse) HasUpdatedAt() bool {
	if o != nil && !isNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *BaseClientResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o BaseClientResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !isNil(o.AuthType) {
		toSerialize["authType"] = o.AuthType
	}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.HasRotatedSecrets) {
		toSerialize["hasRotatedSecrets"] = o.HasRotatedSecrets
	}
	if !isNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !isNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableBaseClientResponse struct {
	value *BaseClientResponse
	isSet bool
}

func (v NullableBaseClientResponse) Get() *BaseClientResponse {
	return v.value
}

func (v *NullableBaseClientResponse) Set(val *BaseClientResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseClientResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseClientResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseClientResponse(val *BaseClientResponse) *NullableBaseClientResponse {
	return &NullableBaseClientResponse{value: val, isSet: true}
}

func (v NullableBaseClientResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseClientResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


