/*
Application Principal Management Service

Handles all administrative requests to manage application identities, including both Agents and Service principals.

API version: 1.0
Contact: info@appdynamics.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package applicationprincipalmanagement

import (
	"encoding/json"
)

// AgentClientsContainer Generic response object which contains an array of AgentClientResponse.
type AgentClientsContainer struct {
	Items []AgentClientResponse `json:"items,omitempty"`
}

// NewAgentClientsContainer instantiates a new AgentClientsContainer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentClientsContainer() *AgentClientsContainer {
	this := AgentClientsContainer{}
	return &this
}

// NewAgentClientsContainerWithDefaults instantiates a new AgentClientsContainer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentClientsContainerWithDefaults() *AgentClientsContainer {
	this := AgentClientsContainer{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *AgentClientsContainer) GetItems() []AgentClientResponse {
	if o == nil || isNil(o.Items) {
		var ret []AgentClientResponse
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentClientsContainer) GetItemsOk() ([]AgentClientResponse, bool) {
	if o == nil || isNil(o.Items) {
    return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *AgentClientsContainer) HasItems() bool {
	if o != nil && !isNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []AgentClientResponse and assigns it to the Items field.
func (o *AgentClientsContainer) SetItems(v []AgentClientResponse) {
	o.Items = v
}

func (o AgentClientsContainer) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableAgentClientsContainer struct {
	value *AgentClientsContainer
	isSet bool
}

func (v NullableAgentClientsContainer) Get() *AgentClientsContainer {
	return v.value
}

func (v *NullableAgentClientsContainer) Set(val *AgentClientsContainer) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentClientsContainer) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentClientsContainer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentClientsContainer(val *AgentClientsContainer) *NullableAgentClientsContainer {
	return &NullableAgentClientsContainer{value: val, isSet: true}
}

func (v NullableAgentClientsContainer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentClientsContainer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


