/*
AppDynamics Cloud Query Service API

An API providing access to observation data using an AppDynamics domain-specific language.  The language is declarative, read-only (it does not allow for data modification) and specific to the AppD MELT model. It presents MELT data (metrics, events, logs, traces) and State in the scope of monitored topology.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudquery

import (
	"encoding/json"
	"fmt"
)

// ModelFieldsInner struct for ModelFieldsInner
type ModelFieldsInner struct {
	ComplexModelResultItem *ComplexModelResultItem
	ModelResultItem *ModelResultItem
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ModelFieldsInner) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ComplexModelResultItem
	err = json.Unmarshal(data, &dst.ComplexModelResultItem);
	if err == nil {
		jsonComplexModelResultItem, _ := json.Marshal(dst.ComplexModelResultItem)
		if string(jsonComplexModelResultItem) == "{}" { // empty struct
			dst.ComplexModelResultItem = nil
		} else {
			return nil // data stored in dst.ComplexModelResultItem, return on the first match
		}
	} else {
		dst.ComplexModelResultItem = nil
	}

	// try to unmarshal JSON data into ModelResultItem
	err = json.Unmarshal(data, &dst.ModelResultItem);
	if err == nil {
		jsonModelResultItem, _ := json.Marshal(dst.ModelResultItem)
		if string(jsonModelResultItem) == "{}" { // empty struct
			dst.ModelResultItem = nil
		} else {
			return nil // data stored in dst.ModelResultItem, return on the first match
		}
	} else {
		dst.ModelResultItem = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ModelFieldsInner)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *ModelFieldsInner) MarshalJSON() ([]byte, error) {
	if src.ComplexModelResultItem != nil {
		return json.Marshal(&src.ComplexModelResultItem)
	}

	if src.ModelResultItem != nil {
		return json.Marshal(&src.ModelResultItem)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableModelFieldsInner struct {
	value *ModelFieldsInner
	isSet bool
}

func (v NullableModelFieldsInner) Get() *ModelFieldsInner {
	return v.value
}

func (v *NullableModelFieldsInner) Set(val *ModelFieldsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableModelFieldsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableModelFieldsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelFieldsInner(val *ModelFieldsInner) *NullableModelFieldsInner {
	return &NullableModelFieldsInner{value: val, isSet: true}
}

func (v NullableModelFieldsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelFieldsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


