// Copyright 2023 Cisco Systems, Inc.
// 
// Licensed under the MPL License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     https://www.mozilla.org/en-US/MPL/2.0/
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
/*
AppDynamics Cloud Connections API

Enables you to manage cloud connections

API version: 1.0.0
Contact: support@appdynamics.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudconnections

import (
	"encoding/json"
)

// AWSRoleDelegationUpdateDetails struct for AWSRoleDelegationUpdateDetails
type AWSRoleDelegationUpdateDetails struct {
	AccessType ConnectionAccessType `json:"accessType"`
	RoleName   string               `json:"roleName"`
}

// NewAWSRoleDelegationUpdateDetails instantiates a new AWSRoleDelegationUpdateDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAWSRoleDelegationUpdateDetails(accessType ConnectionAccessType, roleName string) *AWSRoleDelegationUpdateDetails {
	this := AWSRoleDelegationUpdateDetails{}
	this.AccessType = accessType
	this.RoleName = roleName
	return &this
}

// NewAWSRoleDelegationUpdateDetailsWithDefaults instantiates a new AWSRoleDelegationUpdateDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAWSRoleDelegationUpdateDetailsWithDefaults() *AWSRoleDelegationUpdateDetails {
	this := AWSRoleDelegationUpdateDetails{}
	var accessType ConnectionAccessType = ROLE_DELEGATION
	this.AccessType = accessType
	return &this
}

// GetAccessType returns the AccessType field value
func (o *AWSRoleDelegationUpdateDetails) GetAccessType() ConnectionAccessType {
	if o == nil {
		var ret ConnectionAccessType
		return ret
	}

	return o.AccessType
}

// GetAccessTypeOk returns a tuple with the AccessType field value
// and a boolean to check if the value has been set.
func (o *AWSRoleDelegationUpdateDetails) GetAccessTypeOk() (*ConnectionAccessType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessType, true
}

// SetAccessType sets field value
func (o *AWSRoleDelegationUpdateDetails) SetAccessType(v ConnectionAccessType) {
	o.AccessType = v
}

// GetRoleName returns the RoleName field value
func (o *AWSRoleDelegationUpdateDetails) GetRoleName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleName
}

// GetRoleNameOk returns a tuple with the RoleName field value
// and a boolean to check if the value has been set.
func (o *AWSRoleDelegationUpdateDetails) GetRoleNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleName, true
}

// SetRoleName sets field value
func (o *AWSRoleDelegationUpdateDetails) SetRoleName(v string) {
	o.RoleName = v
}

func (o AWSRoleDelegationUpdateDetails) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["accessType"] = o.AccessType
	}
	if true {
		toSerialize["roleName"] = o.RoleName
	}
	return json.Marshal(toSerialize)
}

type NullableAWSRoleDelegationUpdateDetails struct {
	value *AWSRoleDelegationUpdateDetails
	isSet bool
}

func (v NullableAWSRoleDelegationUpdateDetails) Get() *AWSRoleDelegationUpdateDetails {
	return v.value
}

func (v *NullableAWSRoleDelegationUpdateDetails) Set(val *AWSRoleDelegationUpdateDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableAWSRoleDelegationUpdateDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableAWSRoleDelegationUpdateDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAWSRoleDelegationUpdateDetails(val *AWSRoleDelegationUpdateDetails) *NullableAWSRoleDelegationUpdateDetails {
	return &NullableAWSRoleDelegationUpdateDetails{value: val, isSet: true}
}

func (v NullableAWSRoleDelegationUpdateDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAWSRoleDelegationUpdateDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
