// Copyright 2023 Cisco Systems, Inc.
// 
// Licensed under the MPL License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     https://www.mozilla.org/en-US/MPL/2.0/
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
/*
AppDynamics Cloud Connections API

Enables you to manage cloud connections

API version: 1.0.0
Contact: support@appdynamics.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudconnections

import (
	"encoding/json"
	"fmt"
)

// ConnectionResponseDetails - struct for ConnectionResponseDetails
type ConnectionResponseDetails struct {
	AWSConnectionResponseDetails *AWSConnectionResponseDetails
	AzureDetails *AzureDetails
}

// AWSConnectionResponseDetailsAsConnectionResponseDetails is a convenience function that returns AWSConnectionResponseDetails wrapped in ConnectionResponseDetails
func AWSConnectionResponseDetailsAsConnectionResponseDetails(v *AWSConnectionResponseDetails) ConnectionResponseDetails {
	return ConnectionResponseDetails{
		AWSConnectionResponseDetails: v,
	}
}

// AzureDetailsAsConnectionResponseDetails is a convenience function that returns AzureDetails wrapped in ConnectionResponseDetails
func AzureDetailsAsConnectionResponseDetails(v *AzureDetails) ConnectionResponseDetails {
	return ConnectionResponseDetails{
		AzureDetails: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ConnectionResponseDetails) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AWSConnectionResponseDetails
	err = newStrictDecoder(data).Decode(&dst.AWSConnectionResponseDetails)
	if err == nil {
		jsonAWSConnectionResponseDetails, _ := json.Marshal(dst.AWSConnectionResponseDetails)
		if string(jsonAWSConnectionResponseDetails) == "{}" { // empty struct
			dst.AWSConnectionResponseDetails = nil
		} else {
			match++
		}
	} else {
		dst.AWSConnectionResponseDetails = nil
	}

	// try to unmarshal data into AzureDetails
	err = newStrictDecoder(data).Decode(&dst.AzureDetails)
	if err == nil {
		jsonAzureDetails, _ := json.Marshal(dst.AzureDetails)
		if string(jsonAzureDetails) == "{}" { // empty struct
			dst.AzureDetails = nil
		} else {
			match++
		}
	} else {
		dst.AzureDetails = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AWSConnectionResponseDetails = nil
		dst.AzureDetails = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ConnectionResponseDetails)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ConnectionResponseDetails)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ConnectionResponseDetails) MarshalJSON() ([]byte, error) {
	if src.AWSConnectionResponseDetails != nil {
		return json.Marshal(&src.AWSConnectionResponseDetails)
	}

	if src.AzureDetails != nil {
		return json.Marshal(&src.AzureDetails)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ConnectionResponseDetails) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.AWSConnectionResponseDetails != nil {
		return obj.AWSConnectionResponseDetails
	}

	if obj.AzureDetails != nil {
		return obj.AzureDetails
	}

	// all schemas are nil
	return nil
}

type NullableConnectionResponseDetails struct {
	value *ConnectionResponseDetails
	isSet bool
}

func (v NullableConnectionResponseDetails) Get() *ConnectionResponseDetails {
	return v.value
}

func (v *NullableConnectionResponseDetails) Set(val *ConnectionResponseDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionResponseDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionResponseDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionResponseDetails(val *ConnectionResponseDetails) *NullableConnectionResponseDetails {
	return &NullableConnectionResponseDetails{value: val, isSet: true}
}

func (v NullableConnectionResponseDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionResponseDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


