/*
AppDynamics Cloud Connections API

Enables you to manage cloud connections

API version: 1.0.0
Contact: support@appdynamics.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudconnections

import (
	"encoding/json"
)

// ConfigurationUpdate struct for ConfigurationUpdate
type ConfigurationUpdate struct {
	// Name of the configuration
	DisplayName *string `json:"displayName,omitempty"`
	Description NullableString `json:"description,omitempty"`
	Details *ConfigurationUpdateDetails `json:"details,omitempty"`
}

// NewConfigurationUpdate instantiates a new ConfigurationUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurationUpdate() *ConfigurationUpdate {
	this := ConfigurationUpdate{}
	return &this
}

// NewConfigurationUpdateWithDefaults instantiates a new ConfigurationUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationUpdateWithDefaults() *ConfigurationUpdate {
	this := ConfigurationUpdate{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *ConfigurationUpdate) GetDisplayName() string {
	if o == nil || isNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationUpdate) GetDisplayNameOk() (*string, bool) {
	if o == nil || isNil(o.DisplayName) {
    return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *ConfigurationUpdate) HasDisplayName() bool {
	if o != nil && !isNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *ConfigurationUpdate) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConfigurationUpdate) GetDescription() string {
	if o == nil || isNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConfigurationUpdate) GetDescriptionOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ConfigurationUpdate) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ConfigurationUpdate) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ConfigurationUpdate) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ConfigurationUpdate) UnsetDescription() {
	o.Description.Unset()
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *ConfigurationUpdate) GetDetails() ConfigurationUpdateDetails {
	if o == nil || isNil(o.Details) {
		var ret ConfigurationUpdateDetails
		return ret
	}
	return *o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationUpdate) GetDetailsOk() (*ConfigurationUpdateDetails, bool) {
	if o == nil || isNil(o.Details) {
    return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *ConfigurationUpdate) HasDetails() bool {
	if o != nil && !isNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given ConfigurationUpdateDetails and assigns it to the Details field.
func (o *ConfigurationUpdate) SetDetails(v ConfigurationUpdateDetails) {
	o.Details = &v
}

func (o ConfigurationUpdate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !isNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	return json.Marshal(toSerialize)
}

type NullableConfigurationUpdate struct {
	value *ConfigurationUpdate
	isSet bool
}

func (v NullableConfigurationUpdate) Get() *ConfigurationUpdate {
	return v.value
}

func (v *NullableConfigurationUpdate) Set(val *ConfigurationUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurationUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurationUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurationUpdate(val *ConfigurationUpdate) *NullableConfigurationUpdate {
	return &NullableConfigurationUpdate{value: val, isSet: true}
}

func (v NullableConfigurationUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurationUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


