// Copyright 2023 Cisco Systems, Inc.
// 
// Licensed under the MPL License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     https://www.mozilla.org/en-US/MPL/2.0/
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.// Copyright 2023 Cisco Systems, Inc.
// 
// Licensed under the MPL License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     https://www.mozilla.org/en-US/MPL/2.0/
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
/*
AppDynamics Cloud Connections API

Enables you to manage cloud connections

API version: 1.0.0
Contact: support@appdynamics.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudconnections

import (
	"encoding/json"
)

// AWSConfigurationAllOf struct for AWSConfigurationAllOf
type AWSConfigurationAllOf struct {
	Details AWSConfigurationDetails `json:"details"`
}

// NewAWSConfigurationAllOf instantiates a new AWSConfigurationAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAWSConfigurationAllOf(details AWSConfigurationDetails) *AWSConfigurationAllOf {
	this := AWSConfigurationAllOf{}
	this.Details = details
	return &this
}

// NewAWSConfigurationAllOfWithDefaults instantiates a new AWSConfigurationAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAWSConfigurationAllOfWithDefaults() *AWSConfigurationAllOf {
	this := AWSConfigurationAllOf{}
	return &this
}

// GetDetails returns the Details field value
func (o *AWSConfigurationAllOf) GetDetails() AWSConfigurationDetails {
	if o == nil {
		var ret AWSConfigurationDetails
		return ret
	}

	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value
// and a boolean to check if the value has been set.
func (o *AWSConfigurationAllOf) GetDetailsOk() (*AWSConfigurationDetails, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Details, true
}

// SetDetails sets field value
func (o *AWSConfigurationAllOf) SetDetails(v AWSConfigurationDetails) {
	o.Details = v
}

func (o AWSConfigurationAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["details"] = o.Details
	}
	return json.Marshal(toSerialize)
}

type NullableAWSConfigurationAllOf struct {
	value *AWSConfigurationAllOf
	isSet bool
}

func (v NullableAWSConfigurationAllOf) Get() *AWSConfigurationAllOf {
	return v.value
}

func (v *NullableAWSConfigurationAllOf) Set(val *AWSConfigurationAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAWSConfigurationAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAWSConfigurationAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAWSConfigurationAllOf(val *AWSConfigurationAllOf) *NullableAWSConfigurationAllOf {
	return &NullableAWSConfigurationAllOf{value: val, isSet: true}
}

func (v NullableAWSConfigurationAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAWSConfigurationAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


