// Copyright 2023 Cisco Systems, Inc.
// 
// Licensed under the MPL License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     https://www.mozilla.org/en-US/MPL/2.0/
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
/*
AppDynamics Cloud Connections API

Enables you to manage cloud connections

API version: 1.0.0
Contact: support@appdynamics.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudconnections

import (
	"encoding/json"
)

// AWSRoleDelegationCreationDetailsAllOf1 struct for AWSRoleDelegationCreationDetailsAllOf1
type AWSRoleDelegationCreationDetailsAllOf1 struct {
	AccountId string `json:"accountId"`
}

// NewAWSRoleDelegationCreationDetailsAllOf1 instantiates a new AWSRoleDelegationCreationDetailsAllOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAWSRoleDelegationCreationDetailsAllOf1(accountId string) *AWSRoleDelegationCreationDetailsAllOf1 {
	this := AWSRoleDelegationCreationDetailsAllOf1{}
	this.AccountId = accountId
	return &this
}

// NewAWSRoleDelegationCreationDetailsAllOf1WithDefaults instantiates a new AWSRoleDelegationCreationDetailsAllOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAWSRoleDelegationCreationDetailsAllOf1WithDefaults() *AWSRoleDelegationCreationDetailsAllOf1 {
	this := AWSRoleDelegationCreationDetailsAllOf1{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *AWSRoleDelegationCreationDetailsAllOf1) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *AWSRoleDelegationCreationDetailsAllOf1) GetAccountIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *AWSRoleDelegationCreationDetailsAllOf1) SetAccountId(v string) {
	o.AccountId = v
}

func (o AWSRoleDelegationCreationDetailsAllOf1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["accountId"] = o.AccountId
	}
	return json.Marshal(toSerialize)
}

type NullableAWSRoleDelegationCreationDetailsAllOf1 struct {
	value *AWSRoleDelegationCreationDetailsAllOf1
	isSet bool
}

func (v NullableAWSRoleDelegationCreationDetailsAllOf1) Get() *AWSRoleDelegationCreationDetailsAllOf1 {
	return v.value
}

func (v *NullableAWSRoleDelegationCreationDetailsAllOf1) Set(val *AWSRoleDelegationCreationDetailsAllOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableAWSRoleDelegationCreationDetailsAllOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableAWSRoleDelegationCreationDetailsAllOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAWSRoleDelegationCreationDetailsAllOf1(val *AWSRoleDelegationCreationDetailsAllOf1) *NullableAWSRoleDelegationCreationDetailsAllOf1 {
	return &NullableAWSRoleDelegationCreationDetailsAllOf1{value: val, isSet: true}
}

func (v NullableAWSRoleDelegationCreationDetailsAllOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAWSRoleDelegationCreationDetailsAllOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


