// Copyright 2023 Cisco Systems, Inc.
// 
// Licensed under the MPL License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     https://www.mozilla.org/en-US/MPL/2.0/
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
/*
AppDynamics Cloud Connections API

Enables you to manage cloud connections

API version: 1.0.0
Contact: support@appdynamics.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudconnections

import (
	"encoding/json"
)

// AccessKeyConnectionResponseDetails struct for AccessKeyConnectionResponseDetails
type AccessKeyConnectionResponseDetails struct {
	AWSAccessKeyDetails
	AccountId string `json:"accountId"`
}

// NewAccessKeyConnectionResponseDetails instantiates a new AccessKeyConnectionResponseDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessKeyConnectionResponseDetails(accountId string, accessType ConnectionAccessType, accessKeyId string, secretAccessKey string) *AccessKeyConnectionResponseDetails {
	this := AccessKeyConnectionResponseDetails{}
	this.AccessType = *NewAccessType(accessType)
	this.AccessKeyId = accessKeyId
	this.SecretAccessKey = secretAccessKey
	this.AccountId = accountId
	return &this
}

// NewAccessKeyConnectionResponseDetailsWithDefaults instantiates a new AccessKeyConnectionResponseDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessKeyConnectionResponseDetailsWithDefaults() *AccessKeyConnectionResponseDetails {
	this := AccessKeyConnectionResponseDetails{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *AccessKeyConnectionResponseDetails) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *AccessKeyConnectionResponseDetails) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *AccessKeyConnectionResponseDetails) SetAccountId(v string) {
	o.AccountId = v
}

func (o AccessKeyConnectionResponseDetails) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedAWSAccessKeyDetails, errAWSAccessKeyDetails := json.Marshal(o.AWSAccessKeyDetails)
	if errAWSAccessKeyDetails != nil {
		return []byte{}, errAWSAccessKeyDetails
	}
	errAWSAccessKeyDetails = json.Unmarshal([]byte(serializedAWSAccessKeyDetails), &toSerialize)
	if errAWSAccessKeyDetails != nil {
		return []byte{}, errAWSAccessKeyDetails
	}
	if true {
		toSerialize["accountId"] = o.AccountId
	}
	return json.Marshal(toSerialize)
}

type NullableAccessKeyConnectionResponseDetails struct {
	value *AccessKeyConnectionResponseDetails
	isSet bool
}

func (v NullableAccessKeyConnectionResponseDetails) Get() *AccessKeyConnectionResponseDetails {
	return v.value
}

func (v *NullableAccessKeyConnectionResponseDetails) Set(val *AccessKeyConnectionResponseDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessKeyConnectionResponseDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessKeyConnectionResponseDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessKeyConnectionResponseDetails(val *AccessKeyConnectionResponseDetails) *NullableAccessKeyConnectionResponseDetails {
	return &NullableAccessKeyConnectionResponseDetails{value: val, isSet: true}
}

func (v NullableAccessKeyConnectionResponseDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessKeyConnectionResponseDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
