/*
AppDynamics Cloud Connections API

Enables you to manage cloud connections

API version: 1.0.0
Contact: support@appdynamics.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudconnections

import (
	"encoding/json"
)

// AWSRoleDelegationUpdateDetailsAllOf struct for AWSRoleDelegationUpdateDetailsAllOf
type AWSRoleDelegationUpdateDetailsAllOf struct {
	RoleName string `json:"roleName"`
}

// NewAWSRoleDelegationUpdateDetailsAllOf instantiates a new AWSRoleDelegationUpdateDetailsAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAWSRoleDelegationUpdateDetailsAllOf(roleName string) *AWSRoleDelegationUpdateDetailsAllOf {
	this := AWSRoleDelegationUpdateDetailsAllOf{}
	this.RoleName = roleName
	return &this
}

// NewAWSRoleDelegationUpdateDetailsAllOfWithDefaults instantiates a new AWSRoleDelegationUpdateDetailsAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAWSRoleDelegationUpdateDetailsAllOfWithDefaults() *AWSRoleDelegationUpdateDetailsAllOf {
	this := AWSRoleDelegationUpdateDetailsAllOf{}
	return &this
}

// GetRoleName returns the RoleName field value
func (o *AWSRoleDelegationUpdateDetailsAllOf) GetRoleName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleName
}

// GetRoleNameOk returns a tuple with the RoleName field value
// and a boolean to check if the value has been set.
func (o *AWSRoleDelegationUpdateDetailsAllOf) GetRoleNameOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.RoleName, true
}

// SetRoleName sets field value
func (o *AWSRoleDelegationUpdateDetailsAllOf) SetRoleName(v string) {
	o.RoleName = v
}

func (o AWSRoleDelegationUpdateDetailsAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["roleName"] = o.RoleName
	}
	return json.Marshal(toSerialize)
}

type NullableAWSRoleDelegationUpdateDetailsAllOf struct {
	value *AWSRoleDelegationUpdateDetailsAllOf
	isSet bool
}

func (v NullableAWSRoleDelegationUpdateDetailsAllOf) Get() *AWSRoleDelegationUpdateDetailsAllOf {
	return v.value
}

func (v *NullableAWSRoleDelegationUpdateDetailsAllOf) Set(val *AWSRoleDelegationUpdateDetailsAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAWSRoleDelegationUpdateDetailsAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAWSRoleDelegationUpdateDetailsAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAWSRoleDelegationUpdateDetailsAllOf(val *AWSRoleDelegationUpdateDetailsAllOf) *NullableAWSRoleDelegationUpdateDetailsAllOf {
	return &NullableAWSRoleDelegationUpdateDetailsAllOf{value: val, isSet: true}
}

func (v NullableAWSRoleDelegationUpdateDetailsAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAWSRoleDelegationUpdateDetailsAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


