// Copyright 2023 Cisco Systems, Inc.
// 
// Licensed under the MPL License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     https://www.mozilla.org/en-US/MPL/2.0/
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
/*
AppDynamics Cloud Connections API

Enables you to manage cloud connections

API version: 1.0.0
Contact: support@appdynamics.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudconnections

import (
	"encoding/json"
)

// AzureConfigurationDetailsAllOf struct for AzureConfigurationDetailsAllOf
type AzureConfigurationDetailsAllOf struct {
	// Azure Resource groups used to fetch metrics
	ResourceGroups []string `json:"resourceGroups,omitempty"`
	Services interface{} `json:"services,omitempty"`
	Regions interface{} `json:"regions,omitempty"`
}

// NewAzureConfigurationDetailsAllOf instantiates a new AzureConfigurationDetailsAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureConfigurationDetailsAllOf() *AzureConfigurationDetailsAllOf {
	this := AzureConfigurationDetailsAllOf{}
	return &this
}

// NewAzureConfigurationDetailsAllOfWithDefaults instantiates a new AzureConfigurationDetailsAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureConfigurationDetailsAllOfWithDefaults() *AzureConfigurationDetailsAllOf {
	this := AzureConfigurationDetailsAllOf{}
	return &this
}

// GetResourceGroups returns the ResourceGroups field value if set, zero value otherwise.
func (o *AzureConfigurationDetailsAllOf) GetResourceGroups() []string {
	if o == nil || isNil(o.ResourceGroups) {
		var ret []string
		return ret
	}
	return o.ResourceGroups
}

// GetResourceGroupsOk returns a tuple with the ResourceGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureConfigurationDetailsAllOf) GetResourceGroupsOk() ([]string, bool) {
	if o == nil || isNil(o.ResourceGroups) {
    return nil, false
	}
	return o.ResourceGroups, true
}

// HasResourceGroups returns a boolean if a field has been set.
func (o *AzureConfigurationDetailsAllOf) HasResourceGroups() bool {
	if o != nil && !isNil(o.ResourceGroups) {
		return true
	}

	return false
}

// SetResourceGroups gets a reference to the given []string and assigns it to the ResourceGroups field.
func (o *AzureConfigurationDetailsAllOf) SetResourceGroups(v []string) {
	o.ResourceGroups = v
}

// GetServices returns the Services field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AzureConfigurationDetailsAllOf) GetServices() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AzureConfigurationDetailsAllOf) GetServicesOk() (*interface{}, bool) {
	if o == nil || isNil(o.Services) {
    return nil, false
	}
	return &o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *AzureConfigurationDetailsAllOf) HasServices() bool {
	if o != nil && isNil(o.Services) {
		return true
	}

	return false
}

// SetServices gets a reference to the given interface{} and assigns it to the Services field.
func (o *AzureConfigurationDetailsAllOf) SetServices(v interface{}) {
	o.Services = v
}

// GetRegions returns the Regions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AzureConfigurationDetailsAllOf) GetRegions() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Regions
}

// GetRegionsOk returns a tuple with the Regions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AzureConfigurationDetailsAllOf) GetRegionsOk() (*interface{}, bool) {
	if o == nil || isNil(o.Regions) {
    return nil, false
	}
	return &o.Regions, true
}

// HasRegions returns a boolean if a field has been set.
func (o *AzureConfigurationDetailsAllOf) HasRegions() bool {
	if o != nil && isNil(o.Regions) {
		return true
	}

	return false
}

// SetRegions gets a reference to the given interface{} and assigns it to the Regions field.
func (o *AzureConfigurationDetailsAllOf) SetRegions(v interface{}) {
	o.Regions = v
}

func (o AzureConfigurationDetailsAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ResourceGroups) {
		toSerialize["resourceGroups"] = o.ResourceGroups
	}
	if o.Services != nil {
		toSerialize["services"] = o.Services
	}
	if o.Regions != nil {
		toSerialize["regions"] = o.Regions
	}
	return json.Marshal(toSerialize)
}

type NullableAzureConfigurationDetailsAllOf struct {
	value *AzureConfigurationDetailsAllOf
	isSet bool
}

func (v NullableAzureConfigurationDetailsAllOf) Get() *AzureConfigurationDetailsAllOf {
	return v.value
}

func (v *NullableAzureConfigurationDetailsAllOf) Set(val *AzureConfigurationDetailsAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureConfigurationDetailsAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureConfigurationDetailsAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureConfigurationDetailsAllOf(val *AzureConfigurationDetailsAllOf) *NullableAzureConfigurationDetailsAllOf {
	return &NullableAzureConfigurationDetailsAllOf{value: val, isSet: true}
}

func (v NullableAzureConfigurationDetailsAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureConfigurationDetailsAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


