/*
AppDynamics Cloud Connections API

Enables you to manage cloud connections

API version: 1.0.0
Contact: support@appdynamics.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudconnections

import (
	"encoding/json"
)

// ConfigurationResourceList struct for ConfigurationResourceList
type ConfigurationResourceList struct {
	Items []BaseConfigurationResource `json:"items"`
}

// NewConfigurationResourceList instantiates a new ConfigurationResourceList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurationResourceList(items []BaseConfigurationResource) *ConfigurationResourceList {
	this := ConfigurationResourceList{}
	this.Items = items
	return &this
}

// NewConfigurationResourceListWithDefaults instantiates a new ConfigurationResourceList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationResourceListWithDefaults() *ConfigurationResourceList {
	this := ConfigurationResourceList{}
	return &this
}

// GetItems returns the Items field value
func (o *ConfigurationResourceList) GetItems() []BaseConfigurationResource {
	if o == nil {
		var ret []BaseConfigurationResource
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ConfigurationResourceList) GetItemsOk() ([]BaseConfigurationResource, bool) {
	if o == nil {
    return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ConfigurationResourceList) SetItems(v []BaseConfigurationResource) {
	o.Items = v
}

func (o ConfigurationResourceList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableConfigurationResourceList struct {
	value *ConfigurationResourceList
	isSet bool
}

func (v NullableConfigurationResourceList) Get() *ConfigurationResourceList {
	return v.value
}

func (v *NullableConfigurationResourceList) Set(val *ConfigurationResourceList) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurationResourceList) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurationResourceList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurationResourceList(val *ConfigurationResourceList) *NullableConfigurationResourceList {
	return &NullableConfigurationResourceList{value: val, isSet: true}
}

func (v NullableConfigurationResourceList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurationResourceList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


