/*
AppDynamics Cloud Connections API

Enables you to manage cloud connections

API version: 1.0.0
Contact: support@appdynamics.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudconnections

import (
	"encoding/json"
)

// AzureConfiguration struct for AzureConfiguration
type AzureConfiguration struct {
	BaseEntity
	Details AzureConfigurationDetails `json:"details"`
}

// NewAzureConfiguration instantiates a new AzureConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureConfiguration(details AzureConfigurationDetails, displayName string, type_ ProviderType) *AzureConfiguration {
	this := AzureConfiguration{}
	this.DisplayName = displayName
	this.Type = type_
	this.Details = details
	return &this
}

// NewAzureConfigurationWithDefaults instantiates a new AzureConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureConfigurationWithDefaults() *AzureConfiguration {
	this := AzureConfiguration{}
	return &this
}

// GetDetails returns the Details field value
func (o *AzureConfiguration) GetDetails() AzureConfigurationDetails {
	if o == nil {
		var ret AzureConfigurationDetails
		return ret
	}

	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value
// and a boolean to check if the value has been set.
func (o *AzureConfiguration) GetDetailsOk() (*AzureConfigurationDetails, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Details, true
}

// SetDetails sets field value
func (o *AzureConfiguration) SetDetails(v AzureConfigurationDetails) {
	o.Details = v
}

func (o AzureConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedBaseEntity, errBaseEntity := json.Marshal(o.BaseEntity)
	if errBaseEntity != nil {
		return []byte{}, errBaseEntity
	}
	errBaseEntity = json.Unmarshal([]byte(serializedBaseEntity), &toSerialize)
	if errBaseEntity != nil {
		return []byte{}, errBaseEntity
	}
	if true {
		toSerialize["details"] = o.Details
	}
	return json.Marshal(toSerialize)
}

type NullableAzureConfiguration struct {
	value *AzureConfiguration
	isSet bool
}

func (v NullableAzureConfiguration) Get() *AzureConfiguration {
	return v.value
}

func (v *NullableAzureConfiguration) Set(val *AzureConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureConfiguration(val *AzureConfiguration) *NullableAzureConfiguration {
	return &NullableAzureConfiguration{value: val, isSet: true}
}

func (v NullableAzureConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


