// Copyright 2023 Cisco Systems, Inc.
// 
// Licensed under the MPL License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     https://www.mozilla.org/en-US/MPL/2.0/
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
/*
AppDynamics Cloud Connections API

Enables you to manage cloud connections

API version: 1.0.0
Contact: support@appdynamics.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudconnections

import (
	"encoding/json"
)

// RoleDelegationConnectionResponseDetailsAllOf struct for RoleDelegationConnectionResponseDetailsAllOf
type RoleDelegationConnectionResponseDetailsAllOf struct {
	// AppDynamics AWS Account ID. Delegates a user to an Identity Access Management (IAM) role in AWS. The AWS IAM role provides AppDynamics access to resources.
	AppDynamicsAwsAccountId *string `json:"appDynamicsAwsAccountId,omitempty"`
	// Returns an external ID for AWS role delegation connections
	ExternalId *string `json:"externalId,omitempty"`
}

// NewRoleDelegationConnectionResponseDetailsAllOf instantiates a new RoleDelegationConnectionResponseDetailsAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleDelegationConnectionResponseDetailsAllOf() *RoleDelegationConnectionResponseDetailsAllOf {
	this := RoleDelegationConnectionResponseDetailsAllOf{}
	return &this
}

// NewRoleDelegationConnectionResponseDetailsAllOfWithDefaults instantiates a new RoleDelegationConnectionResponseDetailsAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleDelegationConnectionResponseDetailsAllOfWithDefaults() *RoleDelegationConnectionResponseDetailsAllOf {
	this := RoleDelegationConnectionResponseDetailsAllOf{}
	return &this
}

// GetAppDynamicsAwsAccountId returns the AppDynamicsAwsAccountId field value if set, zero value otherwise.
func (o *RoleDelegationConnectionResponseDetailsAllOf) GetAppDynamicsAwsAccountId() string {
	if o == nil || isNil(o.AppDynamicsAwsAccountId) {
		var ret string
		return ret
	}
	return *o.AppDynamicsAwsAccountId
}

// GetAppDynamicsAwsAccountIdOk returns a tuple with the AppDynamicsAwsAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleDelegationConnectionResponseDetailsAllOf) GetAppDynamicsAwsAccountIdOk() (*string, bool) {
	if o == nil || isNil(o.AppDynamicsAwsAccountId) {
    return nil, false
	}
	return o.AppDynamicsAwsAccountId, true
}

// HasAppDynamicsAwsAccountId returns a boolean if a field has been set.
func (o *RoleDelegationConnectionResponseDetailsAllOf) HasAppDynamicsAwsAccountId() bool {
	if o != nil && !isNil(o.AppDynamicsAwsAccountId) {
		return true
	}

	return false
}

// SetAppDynamicsAwsAccountId gets a reference to the given string and assigns it to the AppDynamicsAwsAccountId field.
func (o *RoleDelegationConnectionResponseDetailsAllOf) SetAppDynamicsAwsAccountId(v string) {
	o.AppDynamicsAwsAccountId = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *RoleDelegationConnectionResponseDetailsAllOf) GetExternalId() string {
	if o == nil || isNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleDelegationConnectionResponseDetailsAllOf) GetExternalIdOk() (*string, bool) {
	if o == nil || isNil(o.ExternalId) {
    return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *RoleDelegationConnectionResponseDetailsAllOf) HasExternalId() bool {
	if o != nil && !isNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *RoleDelegationConnectionResponseDetailsAllOf) SetExternalId(v string) {
	o.ExternalId = &v
}

func (o RoleDelegationConnectionResponseDetailsAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.AppDynamicsAwsAccountId) {
		toSerialize["appDynamicsAwsAccountId"] = o.AppDynamicsAwsAccountId
	}
	if !isNil(o.ExternalId) {
		toSerialize["externalId"] = o.ExternalId
	}
	return json.Marshal(toSerialize)
}

type NullableRoleDelegationConnectionResponseDetailsAllOf struct {
	value *RoleDelegationConnectionResponseDetailsAllOf
	isSet bool
}

func (v NullableRoleDelegationConnectionResponseDetailsAllOf) Get() *RoleDelegationConnectionResponseDetailsAllOf {
	return v.value
}

func (v *NullableRoleDelegationConnectionResponseDetailsAllOf) Set(val *RoleDelegationConnectionResponseDetailsAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleDelegationConnectionResponseDetailsAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleDelegationConnectionResponseDetailsAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleDelegationConnectionResponseDetailsAllOf(val *RoleDelegationConnectionResponseDetailsAllOf) *NullableRoleDelegationConnectionResponseDetailsAllOf {
	return &NullableRoleDelegationConnectionResponseDetailsAllOf{value: val, isSet: true}
}

func (v NullableRoleDelegationConnectionResponseDetailsAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleDelegationConnectionResponseDetailsAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


