/*
AppDynamics Cloud Connections API

Enables you to manage cloud connections

API version: 1.0.0
Contact: support@appdynamics.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudconnections

import (
	"encoding/json"
)

// ConnectionRequestAllOf struct for ConnectionRequestAllOf
type ConnectionRequestAllOf struct {
	Details ConnectionRequestDetails `json:"details"`
}

// NewConnectionRequestAllOf instantiates a new ConnectionRequestAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionRequestAllOf(details ConnectionRequestDetails) *ConnectionRequestAllOf {
	this := ConnectionRequestAllOf{}
	this.Details = details
	return &this
}

// NewConnectionRequestAllOfWithDefaults instantiates a new ConnectionRequestAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionRequestAllOfWithDefaults() *ConnectionRequestAllOf {
	this := ConnectionRequestAllOf{}
	return &this
}

// GetDetails returns the Details field value
func (o *ConnectionRequestAllOf) GetDetails() ConnectionRequestDetails {
	if o == nil {
		var ret ConnectionRequestDetails
		return ret
	}

	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value
// and a boolean to check if the value has been set.
func (o *ConnectionRequestAllOf) GetDetailsOk() (*ConnectionRequestDetails, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Details, true
}

// SetDetails sets field value
func (o *ConnectionRequestAllOf) SetDetails(v ConnectionRequestDetails) {
	o.Details = v
}

func (o ConnectionRequestAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["details"] = o.Details
	}
	return json.Marshal(toSerialize)
}

type NullableConnectionRequestAllOf struct {
	value *ConnectionRequestAllOf
	isSet bool
}

func (v NullableConnectionRequestAllOf) Get() *ConnectionRequestAllOf {
	return v.value
}

func (v *NullableConnectionRequestAllOf) Set(val *ConnectionRequestAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionRequestAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionRequestAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionRequestAllOf(val *ConnectionRequestAllOf) *NullableConnectionRequestAllOf {
	return &NullableConnectionRequestAllOf{value: val, isSet: true}
}

func (v NullableConnectionRequestAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionRequestAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


