/*
AppDynamics Cloud Connections API

Enables you to manage cloud connections

API version: 1.0.0
Contact: support@appdynamics.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudconnections

import (
	"encoding/json"
)

// AzureBaseDetails struct for AzureBaseDetails
type AzureBaseDetails struct {
	ClientId string `json:"clientId"`
	ClientSecret string `json:"clientSecret"`
}

// NewAzureBaseDetails instantiates a new AzureBaseDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureBaseDetails(clientId string, clientSecret string) *AzureBaseDetails {
	this := AzureBaseDetails{}
	this.ClientId = clientId
	this.ClientSecret = clientSecret
	return &this
}

// NewAzureBaseDetailsWithDefaults instantiates a new AzureBaseDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureBaseDetailsWithDefaults() *AzureBaseDetails {
	this := AzureBaseDetails{}
	return &this
}

// GetClientId returns the ClientId field value
func (o *AzureBaseDetails) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *AzureBaseDetails) GetClientIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *AzureBaseDetails) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecret returns the ClientSecret field value
func (o *AzureBaseDetails) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *AzureBaseDetails) GetClientSecretOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *AzureBaseDetails) SetClientSecret(v string) {
	o.ClientSecret = v
}

func (o AzureBaseDetails) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["clientId"] = o.ClientId
	}
	if true {
		toSerialize["clientSecret"] = o.ClientSecret
	}
	return json.Marshal(toSerialize)
}

type NullableAzureBaseDetails struct {
	value *AzureBaseDetails
	isSet bool
}

func (v NullableAzureBaseDetails) Get() *AzureBaseDetails {
	return v.value
}

func (v *NullableAzureBaseDetails) Set(val *AzureBaseDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureBaseDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureBaseDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureBaseDetails(val *AzureBaseDetails) *NullableAzureBaseDetails {
	return &NullableAzureBaseDetails{value: val, isSet: true}
}

func (v NullableAzureBaseDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureBaseDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


