// Copyright 2023 Cisco Systems, Inc.
// 
// Licensed under the MPL License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     https://www.mozilla.org/en-US/MPL/2.0/
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
/*
AppDynamics Cloud Connections API

Enables you to manage cloud connections

API version: 1.0.0
Contact: support@appdynamics.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudconnections

import (
	"encoding/json"
)

// AWSRoleDelegationCreationDetails struct for AWSRoleDelegationCreationDetails
type AWSRoleDelegationCreationDetails struct {
	AccessType ConnectionAccessType `json:"accessType"`
	AccountId  string               `json:"accountId"`
}

// NewAWSRoleDelegationCreationDetails instantiates a new AWSRoleDelegationCreationDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAWSRoleDelegationCreationDetails(accessType ConnectionAccessType, accountId string) *AWSRoleDelegationCreationDetails {
	this := AWSRoleDelegationCreationDetails{}
	this.AccessType = accessType
	this.AccountId = accountId
	return &this
}

// NewAWSRoleDelegationCreationDetailsWithDefaults instantiates a new AWSRoleDelegationCreationDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAWSRoleDelegationCreationDetailsWithDefaults() *AWSRoleDelegationCreationDetails {
	this := AWSRoleDelegationCreationDetails{}
	var accessType ConnectionAccessType = ROLE_DELEGATION
	this.AccessType = accessType
	return &this
}

// GetAccessType returns the AccessType field value
func (o *AWSRoleDelegationCreationDetails) GetAccessType() ConnectionAccessType {
	if o == nil {
		var ret ConnectionAccessType
		return ret
	}

	return o.AccessType
}

// GetAccessTypeOk returns a tuple with the AccessType field value
// and a boolean to check if the value has been set.
func (o *AWSRoleDelegationCreationDetails) GetAccessTypeOk() (*ConnectionAccessType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessType, true
}

// SetAccessType sets field value
func (o *AWSRoleDelegationCreationDetails) SetAccessType(v ConnectionAccessType) {
	o.AccessType = v
}

// GetAccountId returns the AccountId field value
func (o *AWSRoleDelegationCreationDetails) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *AWSRoleDelegationCreationDetails) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *AWSRoleDelegationCreationDetails) SetAccountId(v string) {
	o.AccountId = v
}

func (o AWSRoleDelegationCreationDetails) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["accessType"] = o.AccessType
	}
	if true {
		toSerialize["accountId"] = o.AccountId
	}
	return json.Marshal(toSerialize)
}

type NullableAWSRoleDelegationCreationDetails struct {
	value *AWSRoleDelegationCreationDetails
	isSet bool
}

func (v NullableAWSRoleDelegationCreationDetails) Get() *AWSRoleDelegationCreationDetails {
	return v.value
}

func (v *NullableAWSRoleDelegationCreationDetails) Set(val *AWSRoleDelegationCreationDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableAWSRoleDelegationCreationDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableAWSRoleDelegationCreationDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAWSRoleDelegationCreationDetails(val *AWSRoleDelegationCreationDetails) *NullableAWSRoleDelegationCreationDetails {
	return &NullableAWSRoleDelegationCreationDetails{value: val, isSet: true}
}

func (v NullableAWSRoleDelegationCreationDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAWSRoleDelegationCreationDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
