/*
AppDynamics Cloud Connections API

Enables you to manage cloud connections

API version: 1.0.0
Contact: support@appdynamics.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudconnections

import (
	"encoding/json"
)

// AzureConfigurationAllOf struct for AzureConfigurationAllOf
type AzureConfigurationAllOf struct {
	Details AzureConfigurationDetails `json:"details"`
}

// NewAzureConfigurationAllOf instantiates a new AzureConfigurationAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureConfigurationAllOf(details AzureConfigurationDetails) *AzureConfigurationAllOf {
	this := AzureConfigurationAllOf{}
	this.Details = details
	return &this
}

// NewAzureConfigurationAllOfWithDefaults instantiates a new AzureConfigurationAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureConfigurationAllOfWithDefaults() *AzureConfigurationAllOf {
	this := AzureConfigurationAllOf{}
	return &this
}

// GetDetails returns the Details field value
func (o *AzureConfigurationAllOf) GetDetails() AzureConfigurationDetails {
	if o == nil {
		var ret AzureConfigurationDetails
		return ret
	}

	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value
// and a boolean to check if the value has been set.
func (o *AzureConfigurationAllOf) GetDetailsOk() (*AzureConfigurationDetails, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Details, true
}

// SetDetails sets field value
func (o *AzureConfigurationAllOf) SetDetails(v AzureConfigurationDetails) {
	o.Details = v
}

func (o AzureConfigurationAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["details"] = o.Details
	}
	return json.Marshal(toSerialize)
}

type NullableAzureConfigurationAllOf struct {
	value *AzureConfigurationAllOf
	isSet bool
}

func (v NullableAzureConfigurationAllOf) Get() *AzureConfigurationAllOf {
	return v.value
}

func (v *NullableAzureConfigurationAllOf) Set(val *AzureConfigurationAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureConfigurationAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureConfigurationAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureConfigurationAllOf(val *AzureConfigurationAllOf) *NullableAzureConfigurationAllOf {
	return &NullableAzureConfigurationAllOf{value: val, isSet: true}
}

func (v NullableAzureConfigurationAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureConfigurationAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


